In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [4]:
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [6]:
data['data'].shape

(569, 30)

In [7]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [12]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [15]:
j = 0
for i in data['feature_names']:
  print(i,":",data['data'][0][j])
  j+=1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [25]:
feature = data['data']
feature

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [26]:
label = data['target']
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [27]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [28]:
feature.shape

(569, 30)

In [29]:
label.shape
print(feature)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [31]:
scale = StandardScaler()

feature = scale.fit_transform(feature)
feature

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [32]:
j = 0
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [43]:
print(feature[568])
#print(label[568])
print(data['target_names'][label[568]],label[568])


[-1.80840125  1.22179204 -1.81438851 -1.34778924 -3.11208479 -1.15075248
 -1.11487284 -1.26181958 -0.8200699  -0.56103238 -0.07027874  0.3830925
 -0.15744905 -0.46615196  0.04934236 -1.16351619 -1.05750068 -1.91344745
  0.75282996 -0.382754   -1.41089258  0.76418957 -1.43273495 -1.07581292
 -1.85901852 -1.2075525  -1.30583065 -1.74506282 -0.04813821 -0.75120669]
benign 1


In [52]:
df_frt = pd.DataFrame(feature , columns = data['feature_names'])
df_lbl = pd.DataFrame(label , columns = ['label'])
df = pd.concat([df_frt, df_lbl], axis=1)
df = df.sample(frac = 1)

#feature = df.values[ : , : 30]
#label = df.values[ : ,30: ]
#df_frt
#df_lbl
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
106    -0.706426     -0.223317       -0.691956  -0.689379         1.269571   
243    -0.107156      1.042608       -0.141243  -0.184551        -1.133686   
437    -0.024792     -0.770177       -0.090167  -0.124256        -0.838349   
259     0.398389      3.320807        0.483201   0.256000         0.707364   
342    -0.871154     -1.007538       -0.843535  -0.799162         0.493868   
..           ...           ...             ...        ...              ...   
137    -0.766069     -0.907474       -0.778867  -0.725500         0.002115   
513     0.128576     -1.310057        0.095601   0.011123         0.139464   
41     -0.902396      0.479458       -0.826648  -0.807125         1.874478   
89      0.145616     -0.942380        0.156563  -0.008501         1.198406   
212     3.971288     -0.190738        3.976130   5.244841         1.269571   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
106         -0.050051       -0.227236            -0.362899      -0.038768   
243         -0.687389       -0.525166            -0.657209      -0.140994   
437         -0.860226       -0.671180            -0.502445      -0.356400   
259          1.128731        1.083503             0.904617       1.020006   
342         -0.253400       -0.437281            -0.400043      -0.130042   
..                ...             ...                  ...            ...   
137         -0.671849       -0.675072            -0.520243      -0.283381   
513         -0.287323       -0.082603            -0.140039      -0.265127   
41           0.330874        0.195866             0.200441       0.304421   
89           0.560187        0.136356             0.560267       1.111279   
212          0.895628        2.903973             2.852321      -0.597362   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
106                0.340564  ...       0.583433        -0.647878   -0.630885   
243               -1.206042  ...       0.107929        -0.275853   -0.306902   
437               -0.541186  ...      -0.667207        -0.180538   -0.229554   
259                0.524852  ...       3.885905         0.567086    0.271451   
342                0.889177  ...      -0.940785        -0.819147   -0.774507   
..                      ...  ...            ...              ...         ...   
137               -0.587967  ...      -0.595556        -0.814083   -0.735833   
513               -0.906928  ...      -1.373949         0.036898   -0.032668   
41                 0.836725  ...       1.573523        -0.596944   -0.644421   
89                 0.093901  ...      -1.211106         0.063706   -0.135330   
212               -1.069952  ...      -1.173652         2.419765    2.845036   

     worst smoothness  worst compactness  worst concavity  \
106          1.597003           0.074651         0.072498   
243         -1.695949          -0.700167        -0.653847   
437         -0.564106          -0.821034        -0.769947   
259          2.451803           1.922000         1.430197   
342          0.413434          -0.211612        -0.202880   
..                ...                ...              ...   
137         -0.586024          -0.569123        -0.634657   
513         -0.441366          -0.391004        -0.110288   
41           2.565776           0.098824         0.624213   
89          -0.204652           0.347555        -0.056556   
212         -0.796437          -0.653093         0.229857   

     worst concave points  worst symmetry  worst fractal dimension  label  
106              0.109537       -0.153294                 0.389251      1  
243             -0.815327       -0.384637                -1.149092      1  
437             -0.610225       -0.284334                -0.643146      1  
259              1.321574        0.988859                 2.020138      0  
342             -0.108204        0.647507                 0.379830   

In [53]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
106    -0.706426     -0.223317       -0.691956  -0.689379         1.269571   
243    -0.107156      1.042608       -0.141243  -0.184551        -1.133686   
437    -0.024792     -0.770177       -0.090167  -0.124256        -0.838349   
259     0.398389      3.320807        0.483201   0.256000         0.707364   
342    -0.871154     -1.007538       -0.843535  -0.799162         0.493868   
..           ...           ...             ...        ...              ...   
137    -0.766069     -0.907474       -0.778867  -0.725500         0.002115   
513     0.128576     -1.310057        0.095601   0.011123         0.139464   
41     -0.902396      0.479458       -0.826648  -0.807125         1.874478   
89      0.145616     -0.942380        0.156563  -0.008501         1.198406   
212     3.971288     -0.190738        3.976130   5.244841         1.269571   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
106         -0.050051       -0.227236            -0.362899      -0.038768   
243         -0.687389       -0.525166            -0.657209      -0.140994   
437         -0.860226       -0.671180            -0.502445      -0.356400   
259          1.128731        1.083503             0.904617       1.020006   
342         -0.253400       -0.437281            -0.400043      -0.130042   
..                ...             ...                  ...            ...   
137         -0.671849       -0.675072            -0.520243      -0.283381   
513         -0.287323       -0.082603            -0.140039      -0.265127   
41           0.330874        0.195866             0.200441       0.304421   
89           0.560187        0.136356             0.560267       1.111279   
212          0.895628        2.903973             2.852321      -0.597362   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
106                0.340564  ...       0.583433        -0.647878   -0.630885   
243               -1.206042  ...       0.107929        -0.275853   -0.306902   
437               -0.541186  ...      -0.667207        -0.180538   -0.229554   
259                0.524852  ...       3.885905         0.567086    0.271451   
342                0.889177  ...      -0.940785        -0.819147   -0.774507   
..                      ...  ...            ...              ...         ...   
137               -0.587967  ...      -0.595556        -0.814083   -0.735833   
513               -0.906928  ...      -1.373949         0.036898   -0.032668   
41                 0.836725  ...       1.573523        -0.596944   -0.644421   
89                 0.093901  ...      -1.211106         0.063706   -0.135330   
212               -1.069952  ...      -1.173652         2.419765    2.845036   

     worst smoothness  worst compactness  worst concavity  \
106          1.597003           0.074651         0.072498   
243         -1.695949          -0.700167        -0.653847   
437         -0.564106          -0.821034        -0.769947   
259          2.451803           1.922000         1.430197   
342          0.413434          -0.211612        -0.202880   
..                ...                ...              ...   
137         -0.586024          -0.569123        -0.634657   
513         -0.441366          -0.391004        -0.110288   
41           2.565776           0.098824         0.624213   
89          -0.204652           0.347555        -0.056556   
212         -0.796437          -0.653093         0.229857   

     worst concave points  worst symmetry  worst fractal dimension  label  
106              0.109537       -0.153294                 0.389251      1  
243             -0.815327       -0.384637                -1.149092      1  
437             -0.610225       -0.284334                -0.643146      1  
259              1.321574        0.988859                 2.020138      0  
342             -0.108204        0.647507                 0.379830   

In [56]:
#500 Training
X_train = feature[:500]
y_train = label[:500]

#35 Validation
X_val = feature[500:535]
y_val = label[500:535]

#34 Testing
X_test = feature[535:]
y_test = label[535:]

In [59]:
model = Sequential()

model.add(Dense(32, activation = 'relu', input_dim = 30))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile( loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [60]:
model.fit( X_train , y_train, epochs = 10, batch_size = 5, validation_data = (X_val, y_val))

Epoch 1/10
100/100 [==============================] - 2s 17ms/step - loss: 0.2505 - accuracy: 0.9420 - val_loss: 0.0815 - val_accuracy: 0.9714
Epoch 2/10
100/100 [==============================] - 1s 7ms/step - loss: 0.0822 - accuracy: 0.9720 - val_loss: 0.0768 - val_accuracy: 0.9714
Epoch 3/10
100/100 [==============================] - 1s 8ms/step - loss: 0.0607 - accuracy: 0.9840 - val_loss: 0.0612 - val_accuracy: 0.9714
Epoch 4/10
100/100 [==============================] - 1s 10ms/step - loss: 0.0417 - accuracy: 0.9880 - val_loss: 0.0542 - val_accuracy: 0.9714
Epoch 5/10
100/100 [==============================] - 1s 8ms/step - loss: 0.0372 - accuracy: 0.9880 - val_loss: 0.1683 - val_accuracy: 0.9714
Epoch 6/10
100/100 [==============================] - 1s 9ms/step - loss: 0.0380 - accuracy: 0.9840 - val_loss: 0.0691 - val_accuracy: 0.9429
Epoch 7/10
100/100 [==============================] - 1s 8ms/step - loss: 0.0270 - accuracy: 0.9900 - val_loss: 0.0614 - val_accuracy: 0.9429
Epoc

In [61]:
model.evaluate(X_test , y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.0189 - accuracy: 1.0000


[0.018918437883257866, 1.0]

In [62]:
model.evaluate(X_val , y_val)

2/2 [==============================] - 0s 7ms/step - loss: 0.0764 - accuracy: 0.9714


[0.07640580832958221, 0.9714285731315613]

In [63]:
for i in range(30):
  sample = X_test[i]
  sample = np.reshape(sample, (1,30))

  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-Malignant")

  if (y_test[i] == 1):
    print("*Banign")
  else:
    print("*Melignant")
  print("-----------")

-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------


In [64]:
t = 0
for i in y_val:
  if (i == 1):
    t += 1

print(t)

26


In [65]:
t = 0
for i in y_test:
  if (i == 1):
    t += 1

print(t)

26


In [ ]:
X_test[0] * -.1

In [ ]:
348/350

In [ ]:
347/350

In [ ]:
32/35